### ISSUE TITLE
Headset does not display content of rendering when UpdateView is disabled

### ISSUE THREAD

**Issue by id144** [tebjan/VVVV.OpenVR#4]
Hi Tebjan!

I've encountered an issue, where the headset does not display content of rendering when UpdateView is disabled. 

I wanted to squeeze out some more FPS out of the patch by disabling the VVVV UI Upates as Timing  (Debug) indicated that significant amount of time is spent by Update View Time. 

Repro:
1 - Open %VVVV%\packs\VVVV.OpenVR\Open 01_OpenVRDemo.v4p
\>headset displays the content of rendering
2 - Create UpdateView node, set its Enable pin to 0
\>rendering Preview in the patch displays correct content, headset and Headset Mirror window of vrcompositor.exe does not and displays only the default room instead.

Reproduced with both vvvv_50beta35_x86 and vvvv_50beta35_x64, using VVVV.OpenVR_AnyCPU_V3.zip - 03.10.16, recent release of DX11 pack.  System Windows 10 Home x64,  GTX1070 with driver version 376.33, HTC Vive.

**Comment by tebjan** [comment]
is it the same when you disable it via the vvvv menu? i've done this several times and it worked. but it seems OpenVR got more picky on what is a 'responding app'.

**Comment by tebjan** [comment]
also try if it makes a difference whether the compositor node is visible in a foreground window, i have seen this influencing the rendering also, but did not find a reproducible behavior.

**Comment by id144** [comment]
Interesting! When I UpdateView enable|disable from the menu, it does not disable the rendering in the headset, on the other hand it's seems that the menu item does not have any impact - the UI of VVVV still updates (the LFO output in the help patch for example).
I've noticed the need for the patch with Compositor to have a focus, however it does not affect the repro scenario above.

vrmonitor.exe starts to report Not Ready (unresponsive) vvvv.exe immediately after the UpdateView node is set to disabled.

**Comment by tebjan** [comment]
could be a vvvv bug... i will add it to our tracker.

**Comment by tebjan** [comment]
regarding the not responsive thing, there are several options how to create a vr app. changing that might fix something: https://github.com/tebjan/VVVV.OpenVR/blob/master/src/VVVV.OpenVR.Core/Core/OpenVRManager.cs#L51

you could try some other options there... but from the description, scene seems to be the correct one.

**Comment by id144** [comment]
Thanks! 

I notice one more thing, not sure if that is related issue, separate issue or an inevitable behavior. When i use S+H to store the texture handle/pointer between output of Info and input of Compositor, the rendering stays still even though app is not reported as unresponsive.  (Why using the info it every frame, when the value stays the same? Seems in this case the logic is reversed, why sharing the texture when no-one is asking for the pointer to it)

**Comment by id144** [comment]
I compiled your repo and attached the Visual Studio debugger. When UpdateView is disable, the Evaluate method of VOpenVRCompositorNode is not executed. Indeed - the output of the node is not used.

The issue happens also when I simply delete the IO boxes of the Compositor output pin Error. Of course - the "output" of the Compositor node is not needed and Evaluate is not executed. 

As a solution it is enough to make sure output of Compositor is used even when UpdateView is disabled. I'm just writing the string length of the Error output Pin to the shared memory.  :)

It resolved the focus issue too! :)

**Comment by tebjan** [comment]
oh, it might be as simple as setting AutoEvalute = true... a classic!

**Comment by tebjan** [comment]
it also explains the S+H problem. S+H also stops evaluation in the graph above it... let me fix that.

**Comment by tebjan** [comment]
can you please test V5? if good, i'll upload it:

[VVVV.OpenVR_AnyCPU_V5.zip](https://github.com/tebjan/VVVV.OpenVR/files/714911/VVVV.OpenVR_AnyCPU_V5.zip)

**Comment by id144** [comment]
Sweet, works well. Thanks Tebjan!

Tested with vvvv_50beta35_x64 and vvvv_50beta35_x86
-UpdateView can be disable, headset still displays the rendering
-Error output can be delete
-VVVV can be minimized

**Comment by tebjan** [comment]
good to know!
