### ISSUE TITLE
vvvv not seen if long startup time

### ISSUE THREAD

**Issue by mediadog** [tebjan/VVVV.OpenVR#6]
I tried this with a pretty large 3D model, which with its textures being loaded takes about 10-15 seconds for vvvv to start cycling.  SteamVR starts, but then shows "(unresponsive) vvvv.exe" with only the default world showing in the HMD.  Nothing I have tried will then make it work, including banging the Init pin.  Everything appears to be working, HMD and controller data is valid, just no vvvv image in the HMD.

I found that setting the OpenVR node Evaluate pin to false and saving the patch, and then only turning it back on after the model and textures have loaded works.

So is there some way to really cause OpenVR to re-initialize?  Why is it not seeing vvvv if there is a delay, is there a timeout?

**Comment by tebjan** [comment]
yes, it seems that a long frame will make OpenVR think that the app is unresponsive or freezed. then only a restart helps because OpenVR has blocked this process. i have not found a way to re-init from that state.

**Comment by tebjan** [comment]
there seems to be a trick in the openvr config file to avoid vvvv going gray if a frame takes longer: https://www.reddit.com/r/Vive/comments/4stfbo/will_basic_head_tracking_work_without_the_base/

might help with this issue, closing for now. re-open if it happens again.
