### ISSUE TITLE
vive tracker only support

### ISSUE THREAD

**Issue by wirmachenbunt** [tebjan/VVVV.OpenVR#8]
allow using just the vive tracker, without headset

**Comment by tebjan** [comment]
currently no vive setup to test it, but i could identify the place that needs a change:
https://github.com/tebjan/VVVV.OpenVR/blob/master/src/VVVV.OpenVR.Core/Core/OpenVRManager.cs#L48

**Comment by tebjan** [comment]
done. 9776f10a332e4f66926bd81b40bc7da87c43e842
